version: '3'
services:
  app:
    build: .
    stdin_open: true  # needed to use console
    tty: true
    depends_on:
      - db
    networks:
      - app-network

  # build db
  db:
    build: world-db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-network

networks:
    app-network:
      driver: bridge
